### ISSUE TITLE
advice  to upload your project on GitHub pages for free 

### ISSUE THREAD

**Issue by EyeRunnMan** [aadi30thakur/covid-tracker-react#1]
try visiting this article [https://medium.com/better-programming/how-to-host-your-react-app-on-github-pages-for-free-919ad201a4cb](url) so that you can upload your react app on GitHub pages for free

**Comment by aadi30thakur** [comment]
thanks for the info but this site is already hosted on firebase at :
https://covid-tracker-by-aadi.web.app/

**Comment by EyeRunnMan** [comment]
why go Firebase when you have GitHub
